### ISSUE TITLE
مشکل در اتصال به درگاه بانک پارسیان

### ISSUE THREAD

**Issue by ErFUN-KH** [Nevercom/php-ipg-ir#4]
منظور از pin در درگاه بانک پارسیان چیه؟
بعد کمی سرچ متوجه شدم در نسخه قدیمی بانک پارسیان pin میداده ولی از وقتی رفته روی سیستم شاپرک شماره ترمينال و شماره پذيرنده میده.
ولی کد شما چند ماهه نوشته شده، من اشتباه میکنم؟

**Comment by Nevercom** [comment]
سلام
مستنداتی که از بانک پارسیان دریافت کردم و مربوط به کمتر از یک سال پیش میشه، به این شکل بوده و شناسه ی پذیرنده همون پین هست.
اگر مستندات جدیدتری در اختیار دارید ممنون میشم برای من ارسال کنید تا بررسی کنم.

ممنون
